/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.compsciia.compsciia;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fernandonunes
 */
public class HomeScreen extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeScreen.class.getName());
    private Student selectedStudent;

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
        initComponents();
        loadTable();
    }

    public final void loadTable() {
        try {
            // 1. Connect to Database
            Connection cnct = ConnectionFactory.getConnection();
            String sql = "SELECT * FROM Students";
            PreparedStatement stmt = cnct.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            // 2. Get Table Model from the GUI JTable
            DefaultTableModel model = (DefaultTableModel) StudentsTable.getModel();
            model.setRowCount(0); // Clear existing data

            // 3. Loop through result set and add rows
            while (rs.next()) {
                Vector<Object> row = new Vector<Object>();
                row.add(rs.getInt("StudentID"));
                row.add(rs.getString("Name"));
                row.add(rs.getDate("Birthdate"));
                row.add(rs.getInt("StudentGroup"));
                row.add(rs.getString("PrevSchool"));
                row.add(rs.getInt("YearofEntry"));
                row.add(rs.getString("Address"));
                // Add the row to the model
                model.addRow(row);
            }
            cnct.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "There was an issue loading the Students table. Please try again");
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        StudentsTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        StudentsTable.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        StudentsTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        StudentsTable.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        ExitButton = new javax.swing.JButton();
        EditStudentButton = new javax.swing.JButton();
        AddStudentButton = new javax.swing.JButton();
        AnalyticsButton = new javax.swing.JButton();
        DeleteStudentButton = new javax.swing.JButton();
        studentProfileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Birthdate", "Group", "Previous School", "Entry", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StudentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(StudentsTable);
        if (StudentsTable.getColumnModel().getColumnCount() > 0) {
            StudentsTable.getColumnModel().getColumn(0).setPreferredWidth(25);
            StudentsTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            StudentsTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            StudentsTable.getColumnModel().getColumn(3).setPreferredWidth(60);
            StudentsTable.getColumnModel().getColumn(3).setMaxWidth(60);
            StudentsTable.getColumnModel().getColumn(5).setMaxWidth(50);
            StudentsTable.getColumnModel().getColumn(6).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        ExitButton.setText("Exit");
        ExitButton.addActionListener(this::ExitButtonActionPerformed);

        EditStudentButton.setText("Edit Student");
        EditStudentButton.addActionListener(this::EditStudentButtonActionPerformed);

        AddStudentButton.setText("Add Student");
        AddStudentButton.addActionListener(this::AddStudentButtonActionPerformed);

        AnalyticsButton.setText("Analytics");
        AnalyticsButton.addActionListener(this::AnalyticsButtonActionPerformed);

        DeleteStudentButton.setText("Delete Student");
        DeleteStudentButton.addActionListener(this::DeleteStudentButtonActionPerformed);

        studentProfileButton.setText("Student Profile");
        studentProfileButton.addActionListener(this::studentProfileButtonActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AnalyticsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(studentProfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddStudentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditStudentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteStudentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton)
                    .addComponent(EditStudentButton)
                    .addComponent(AddStudentButton)
                    .addComponent(AnalyticsButton)
                    .addComponent(DeleteStudentButton)
                    .addComponent(studentProfileButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnalyticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyticsButtonActionPerformed
        Analytics analytics = new Analytics();
        analytics.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AnalyticsButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void AddStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentButtonActionPerformed
        AddStudent addStd = new AddStudent();
        addStd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddStudentButtonActionPerformed

    private void StudentsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentsTableMouseClicked
        int row = StudentsTable.getSelectedRow();
        if (row == -1) {
            row = 0;
        }
        int id = Integer.parseInt(StudentsTable.getValueAt(row, 0).toString());
        selectedStudent = DBTools.searchStudent(id);
//        System.out.println(id+" | "+selectedStudent.getName());
    }//GEN-LAST:event_StudentsTableMouseClicked

    private void EditStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditStudentButtonActionPerformed
        EditStudent editStudent = new EditStudent(selectedStudent);
        editStudent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditStudentButtonActionPerformed

    private void DeleteStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteStudentButtonActionPerformed
        // TODO add your handling code here:
        DBTools.deleteStudent(selectedStudent.getId());
        this.loadTable();
    }//GEN-LAST:event_DeleteStudentButtonActionPerformed

    private void studentProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentProfileButtonActionPerformed
        // TODO add your handling code here:
        StudentProfile stdProfile = new StudentProfile(selectedStudent);
        stdProfile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studentProfileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStudentButton;
    private javax.swing.JButton AnalyticsButton;
    private javax.swing.JButton DeleteStudentButton;
    private javax.swing.JButton EditStudentButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTable StudentsTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton studentProfileButton;
    // End of variables declaration//GEN-END:variables
}
